import {
  Badge,
  Code,
  Container,
  ContentPlaceholder,
  CoverPage,
  DocsPageTitle,
  Gallery,
  Icon,
  InteractiveContentPlaceholder,
  Link,
  Placement,
  Row,
  SidebarItem,
  StatusIndicator,
  TokenPreview,
  Tooltip,
  VisualWrapper,
} from './src/components';

export const Storybook = {
  Code,
  Container,
  ContentPlaceholder,
  Gallery,
  Placement,
  Row,
  Badge,
  StatusIndicator,
  Tooltip,
  Icon,
  SidebarItem,
  CoverPage,
  DocsPageTitle,
  Link,
  TokenPreview,
  InteractiveContentPlaceholder,
  VisualWrapper,
};
export type { BadgeProps, StatusIndicatorProps } from './src/components';
export {
  colorPalettes,
  tableBorderStyles,
  tableHeaderStyles,
  tableRowBackgroundStyles,
  textStyles,
} from './src/components/shared-styles';
