import {
  _baseBadgeTheme,
  _baseCalendarTheme,
  _descriptionTheme,
  _labelTheme,
  _mainLabelTheme,
  _menuFooterTheme,
  _menuTitleTheme,
  _paragraphListTheme,
  _paragraphTheme,
  _sectionLabelTheme,
  accordionTheme,
  actionAreaTheme,
  actionBarTheme,
  alternativeSlideTheme,
  amountFieldTheme,
  amountInputTheme,
  avatarGroupTheme,
  avatarImageControlTheme,
  avatarTheme,
  avatarWithDetailsTheme,
  badgeTheme,
  baseIconTheme,
  baseModalTheme,
  basePopoverTheme,
  baseSelectTheme,
  baseSheetTheme,
  baseVirtualCardDetailsTheme,
  baseVirtualCardTheme,
  beaconTheme,
  blanketTheme,
  bottomSheetMenuTheme,
  brandSymbolTheme,
  brandTheme,
  buttonGroupTheme,
  buttonTheme,
  calendarLegendTheme,
  calendarTheme,
  cardTheme,
  checkboxTheme,
  chipTheme,
  circularProgressTheme,
  collapsibleCardTheme,
  collapsibleTheme,
  comboboxTheme,
  containerTheme,
  counterTheme,
  currencyTheme,
  customInputContainerTheme,
  dateFieldTheme,
  dividerTheme,
  drawerTheme,
  dropdownListTheme,
  dropzoneTheme,
  externalLayoutTheme,
  fileAttachmentTheme,
  fileInputTheme,
  fileUploadTheme,
  flagIconTheme,
  flatMenuTheme,
  floatingCalendarTheme,
  floatingContainerTheme,
  floatingMenuTheme,
  formFieldTheme,
  formLineItemsTheme,
  formTheme,
  groupItemTheme,
  groupTheme,
  hiddenOptionInputTheme,
  iconButtonTheme,
  illustrationTheme,
  imageTheme,
  interactiveCardTheme,
  interactiveTagTheme,
  largeFileUploadTheme,
  layoutTheme,
  linearProgressTheme,
  linkTheme,
  loaderTheme,
  loadingContainerTheme,
  logoTheme,
  lottieTheme,
  menuItemTheme,
  multiSelectTheme,
  nakedButtonTheme,
  navigationItemTheme,
  panelTheme,
  popoverTheme,
  promotionalModalTheme,
  radioGroupTheme,
  radioTheme,
  searchBarTheme,
  sectionBannerTheme,
  securedTextFieldTheme,
  segmentedControlTheme,
  selectionCardTheme,
  selectNewTheme,
  skeletonTextTheme,
  skeletonTheme,
  spinnerTheme,
  splitScreenTheme,
  stackedContainerTheme,
  statusIndicatorTheme,
  switchTheme,
  tableAmountCellTheme,
  tableCellTheme,
  tableDataCellTheme,
  tableHeaderBaseCellTheme,
  tableHeaderCellTheme,
  tableHeaderMenuTriggerCellTheme,
  tableHeaderSortableCellTheme,
  tableMobileContainerTheme,
  tableSelectCellTheme,
  tableTheme,
  tabsTheme,
  tagTheme,
  textAreaTheme,
  textFieldTheme,
  textTheme,
  toastTheme,
  tooltipTheme,
  trackerStepTheme,
  trackerTheme,
  verificationCodeFieldTheme,
  virtualCardTheme,
} from '../components/components.theme';
import { type ComponentMultiStyleConfig, type ComponentSingleStyleConfig } from './component-style-config-types';

const SingleStyleConfigComponents = {
  AmountField: amountFieldTheme,
  ActionArea: actionAreaTheme,
  _BaseBadge: _baseBadgeTheme,
  BaseIcon: baseIconTheme,
  Chip: chipTheme,
  FileInput: fileInputTheme,
  PromotionalModal: promotionalModalTheme,
  Counter: counterTheme,
  _Description: _descriptionTheme,
  _MenuTitle: _menuTitleTheme,
  _MenuFooter: _menuFooterTheme,
  FlagIcon: flagIconTheme,
  BrandSymbol: brandSymbolTheme,
  Brand: brandTheme,
  Calendar: calendarTheme,
  _SectionLabel: _sectionLabelTheme,
  Illustration: illustrationTheme,
  Link: linkTheme,
  Logo: logoTheme,
  Lottie: lottieTheme,
  NavigationItem: navigationItemTheme,
  RadioGroup: radioGroupTheme,
  Tracker: trackerTheme,
  TableCell: tableCellTheme,
  TableHeaderBaseCell: tableHeaderBaseCellTheme,
  TableDataCell: tableDataCellTheme,
  TableHeaderCell: tableHeaderCellTheme,
  TableMenuTriggerHeaderCell: tableHeaderMenuTriggerCellTheme,
  Container: containerTheme,
  Group: groupTheme,
  Skeleton: skeletonTheme,
  SkeletonText: skeletonTextTheme,
  GroupItem: groupItemTheme,
  Text: textTheme,
  FlatMenu: flatMenuTheme,
  DropdownList: dropdownListTheme,
  MenuItem: menuItemTheme,
  IconButton: iconButtonTheme,
  AlternativeSlide: alternativeSlideTheme,
  FloatingContainer: floatingContainerTheme,
  Tag: tagTheme,
  ButtonGroup: buttonGroupTheme,
};
export type SingleStyleConfigComponents = typeof SingleStyleConfigComponents;

const MultiStyleConfigComponents = {
  AmountInput: amountInputTheme,
  BaseModal: baseModalTheme,
  BaseSheet: baseSheetTheme,
  _Paragraph: _paragraphTheme,
  _ParagraphList: _paragraphListTheme,
  _MainLabel: _mainLabelTheme,
  _Label: _labelTheme,
  TextArea: textAreaTheme,
  Input: textFieldTheme,
  BaseSelect: baseSelectTheme,
  Accordion: accordionTheme,
  Avatar: avatarTheme,
  Button: buttonTheme,
  Card: cardTheme,
  InteractiveCard: interactiveCardTheme,
  Checkbox: checkboxTheme,
  Badge: badgeTheme,
  _BaseCalendar: _baseCalendarTheme,
  CalendarLegend: calendarLegendTheme,
  Currency: currencyTheme,
  Dropzone: dropzoneTheme,
  FileUpload: fileUploadTheme,
  DateField: dateFieldTheme,
  Divider: dividerTheme,
  FloatingCalendar: floatingCalendarTheme,
  Collapsible: collapsibleTheme,
  CollapsibleCard: collapsibleCardTheme,
  FormField: formFieldTheme,
  Form: formTheme,
  Image: imageTheme,
  AvatarWithDetails: avatarWithDetailsTheme,
  BasePopover: basePopoverTheme,
  Popover: popoverTheme,
  Beacon: beaconTheme,
  LinearProgress: linearProgressTheme,
  CircularProgress: circularProgressTheme,
  Radio: radioTheme,
  SearchBar: searchBarTheme,
  Switch: switchTheme,
  Tabs: tabsTheme,
  Toast: toastTheme,
  Table: tableTheme,
  TableMobileContainer: tableMobileContainerTheme,
  TableSelectCell: tableSelectCellTheme,
  TableHeaderSortableCell: tableHeaderSortableCellTheme,
  Tooltip: tooltipTheme,
  TrackerStep: trackerStepTheme,
  SectionBanner: sectionBannerTheme,
  AvatarImageControl: avatarImageControlTheme,
  FileAttachment: fileAttachmentTheme,
  LargeFileUpload: largeFileUploadTheme,
  TableAmountCell: tableAmountCellTheme,
  CustomInputContainer: customInputContainerTheme,
  LoadingContainer: loadingContainerTheme,
  Loader: loaderTheme,
  Drawer: drawerTheme,
  StatusIndicator: statusIndicatorTheme,
  Spinner: spinnerTheme,
  AvatarGroup: avatarGroupTheme,
  VerificationCodeField: verificationCodeFieldTheme,
  HiddenOptionInput: hiddenOptionInputTheme,
  SegmentedControl: segmentedControlTheme,
  Blanket: blanketTheme,
  ActionBar: actionBarTheme,
  BaseVirtualCard: baseVirtualCardTheme,
  BaseVirtualCardDetails: baseVirtualCardDetailsTheme,
  VirtualCard: virtualCardTheme,
  SecuredTextField: securedTextFieldTheme,
  StackedContainer: stackedContainerTheme,
  SelectNew: selectNewTheme,
  MultiSelect: multiSelectTheme,
  Combobox: comboboxTheme,
  Panel: panelTheme,
  BottomSheetMenu: bottomSheetMenuTheme,
  FloatingMenu: floatingMenuTheme,
  NakedButton: nakedButtonTheme,
  InteractiveTag: interactiveTagTheme,
  SelectionCard: selectionCardTheme,
  // layouts
  ExternalLayout: externalLayoutTheme,
  SplitScreen: splitScreenTheme,
  Layout: layoutTheme,
  FormLineItems: formLineItemsTheme,
  Menu: {
    baseStyle: {
      item: { ...menuItemTheme.baseStyle },
    },
  },
};
type MultiStyleConfigComponents = typeof MultiStyleConfigComponents;

export const components = {
  ...MultiStyleConfigComponents,
  ...SingleStyleConfigComponents,
};

export type MultiStyleConfigComponentsParts = {
  [Property in keyof MultiStyleConfigComponents]: InferInferComponentMultiStyleParts<
    (typeof MultiStyleConfigComponents)[Property]
  >;
};

export type MultiStyleConfigComponentsProps = {
  [Property in keyof MultiStyleConfigComponents]: InferComponentMultiStyleProps<
    (typeof MultiStyleConfigComponents)[Property]
  >;
};

export type SingleStyleConfigComponentsProps = {
  [Property in keyof SingleStyleConfigComponents]: InferComponentSingleStyleProps<
    SingleStyleConfigComponents[Property]
  >;
};

/* eslint-disable @typescript-eslint/no-explicit-any */
type InferComponentSingleStyleProps<C extends ComponentSingleStyleConfig<any>> =
  C extends ComponentSingleStyleConfig<infer T> ? T : unknown;

type InferInferComponentMultiStyleParts<C extends ComponentMultiStyleConfig<any, any>> =
  C extends ComponentMultiStyleConfig<infer T, any> ? T : unknown;

type InferComponentMultiStyleProps<C extends ComponentMultiStyleConfig<any, any>> =
  C extends ComponentMultiStyleConfig<any, infer T> ? T : unknown;
