/* eslint-disable max-lines */
// Auto-generated file by https://github.com/melio/penny/actions/workflows/sync-illustrations.yml

import { type ComponentType } from 'react';

import { type ThemeIllustrationType } from './defaultIllustrations.generated.types';

const getIllustrationPath = (cdnUrl: string, name: string) => `${cdnUrl}/assets/1.0.0/illustrations/${name}.svg`;

export const getDefaultIllustrations = (cdnUrl: string): Record<ThemeIllustrationType, ComponentType | string> => ({
  academy: getIllustrationPath(cdnUrl, 'academy'),
  'add-card': getIllustrationPath(cdnUrl, 'add-card'),
  'add-user': getIllustrationPath(cdnUrl, 'add-user'),
  add: getIllustrationPath(cdnUrl, 'add'),
  announce: getIllustrationPath(cdnUrl, 'announce'),
  'approval-workflows': getIllustrationPath(cdnUrl, 'approval-workflows'),
  approve: getIllustrationPath(cdnUrl, 'approve'),
  'bank-missing': getIllustrationPath(cdnUrl, 'bank-missing'),
  'bank-success': getIllustrationPath(cdnUrl, 'bank-success'),
  bank: getIllustrationPath(cdnUrl, 'bank'),
  blocked: getIllustrationPath(cdnUrl, 'blocked'),
  calendar: getIllustrationPath(cdnUrl, 'calendar'),
  camera: getIllustrationPath(cdnUrl, 'camera'),
  card: getIllustrationPath(cdnUrl, 'card'),
  celebration: getIllustrationPath(cdnUrl, 'celebration'),
  construction: getIllustrationPath(cdnUrl, 'construction'),
  'create-invoice': getIllustrationPath(cdnUrl, 'create-invoice'),
  'customer-add': getIllustrationPath(cdnUrl, 'customer-add'),
  'customize-invoice': getIllustrationPath(cdnUrl, 'customize-invoice'),
  customize: getIllustrationPath(cdnUrl, 'customize'),
  declined: getIllustrationPath(cdnUrl, 'declined'),
  discount: getIllustrationPath(cdnUrl, 'discount'),
  edit: getIllustrationPath(cdnUrl, 'edit'),
  error: getIllustrationPath(cdnUrl, 'error'),
  expired: getIllustrationPath(cdnUrl, 'expired'),
  faq: getIllustrationPath(cdnUrl, 'faq'),
  fast: getIllustrationPath(cdnUrl, 'fast'),
  'fun-fact': getIllustrationPath(cdnUrl, 'fun-fact'),
  gift: getIllustrationPath(cdnUrl, 'gift'),
  grow: getIllustrationPath(cdnUrl, 'grow'),
  invoice: getIllustrationPath(cdnUrl, 'invoice'),
  missing: getIllustrationPath(cdnUrl, 'missing'),
  mobile: getIllustrationPath(cdnUrl, 'mobile'),
  'money-success': getIllustrationPath(cdnUrl, 'money-success'),
  'network-download': getIllustrationPath(cdnUrl, 'network-download'),
  'network-error': getIllustrationPath(cdnUrl, 'network-error'),
  'network-pay': getIllustrationPath(cdnUrl, 'network-pay'),
  'new-email': getIllustrationPath(cdnUrl, 'new-email'),
  'no-items': getIllustrationPath(cdnUrl, 'no-items'),
  notification: getIllustrationPath(cdnUrl, 'notification'),
  'page-not-found': getIllustrationPath(cdnUrl, 'page-not-found'),
  'paper-check': getIllustrationPath(cdnUrl, 'paper-check'),
  'pay-zero': getIllustrationPath(cdnUrl, 'pay-zero'),
  pay: getIllustrationPath(cdnUrl, 'pay'),
  'payment-request-link': getIllustrationPath(cdnUrl, 'payment-request-link'),
  'payout-add': getIllustrationPath(cdnUrl, 'payout-add'),
  pending: getIllustrationPath(cdnUrl, 'pending'),
  processing: getIllustrationPath(cdnUrl, 'processing'),
  product: getIllustrationPath(cdnUrl, 'product'),
  question: getIllustrationPath(cdnUrl, 'question'),
  'save-money': getIllustrationPath(cdnUrl, 'save-money'),
  security: getIllustrationPath(cdnUrl, 'security'),
  sent: getIllustrationPath(cdnUrl, 'sent'),
  'set-up-account': getIllustrationPath(cdnUrl, 'set-up-account'),
  'single-use-card': getIllustrationPath(cdnUrl, 'single-use-card'),
  'small-business': getIllustrationPath(cdnUrl, 'small-business'),
  success: getIllustrationPath(cdnUrl, 'success'),
  'sync-accounts': getIllustrationPath(cdnUrl, 'sync-accounts'),
  'sync-user': getIllustrationPath(cdnUrl, 'sync-user'),
  'tax-form': getIllustrationPath(cdnUrl, 'tax-form'),
  troubleshooting: getIllustrationPath(cdnUrl, 'troubleshooting'),
  'under-review': getIllustrationPath(cdnUrl, 'under-review'),
  'upgrade-plan': getIllustrationPath(cdnUrl, 'upgrade-plan'),
  'user-approve': getIllustrationPath(cdnUrl, 'user-approve'),
  'user-management': getIllustrationPath(cdnUrl, 'user-management'),
  'vendor-add': getIllustrationPath(cdnUrl, 'vendor-add'),
  warning: getIllustrationPath(cdnUrl, 'warning'),
});
