import { type ComboboxOption, type ComboboxSection } from '../Combobox.types';

export type City = ComboboxOption<string> & { description: string };

export const cities: City[] = [
  { label: 'Albuquerque', value: 'albuquerque', description: 'Population: 560,513' },
  { label: 'Arlington', value: 'arlington', description: 'Population: 398,112' },
  { label: 'Atlanta', value: 'atlanta', description: 'Population: 488,800' },
  { label: 'Austin', value: 'austin', description: 'Population: 978,908' },
  { label: 'Baltimore', value: 'baltimore', description: 'Population: 593,490' },
  { label: 'Boston', value: 'boston', description: 'Population: 692,600' },
  { label: 'Charlotte', value: 'charlotte', description: 'Population: 885,708' },
  { label: 'Chicago', value: 'chicago', description: 'Population: 2,693,976' },
  { label: 'Chula Vista', value: 'chula_vista', description: 'Population: 275,487' },
  { label: 'Cincinnati', value: 'cincinnati', description: 'Population: 302,605' },
  { label: 'Cleveland', value: 'cleveland', description: 'Population: 381,009' },
  { label: 'Colorado Springs', value: 'colorado_springs', description: 'Population: 478,221' },
  { label: 'Columbus', value: 'columbus', description: 'Population: 898,553' },
  { label: 'Dallas', value: 'dallas', description: 'Population: 1,343,573' },
  { label: 'Denver', value: 'denver', description: 'Population: 727,211' },
  { label: 'Detroit', value: 'detroit', description: 'Population: 670,031' },
  { label: 'Durham', value: 'durham', description: 'Population: 278,993' },
  { label: 'El Paso', value: 'el_paso', description: 'Population: 681,728' },
  { label: 'Fort Lauderdale', value: 'fort_lauderdale', description: 'Population: 182,437' },
  { label: 'Fort Worth', value: 'fort_worth', description: 'Population: 909,585' },
  { label: 'Fresno', value: 'fresno', description: 'Population: 531,576' },
  { label: 'Greensboro', value: 'greensboro', description: 'Population: 296,710' },
  { label: 'Henderson', value: 'henderson', description: 'Population: 320,189' },
  { label: 'Houston', value: 'houston', description: 'Population: 2,320,268' },
  { label: 'Indianapolis', value: 'indianapolis', description: 'Population: 876,384' },
  { label: 'Irvine', value: 'irvine', description: 'Population: 287,401' },
  { label: 'Jacksonville', value: 'jacksonville', description: 'Population: 911,507' },
  { label: 'Jersey City', value: 'jersey_city', description: 'Population: 265,549' },
  { label: 'Kansas City', value: 'kansas_city', description: 'Population: 495,327' },
  { label: 'Las Vegas', value: 'las_vegas', description: 'Population: 651,319' },
  { label: 'Lexington', value: 'lexington', description: 'Population: 323,152' },
  { label: 'Lincoln', value: 'lincoln', description: 'Population: 289,102' },
  { label: 'Long Beach', value: 'long_beach', description: 'Population: 462,628' },
  { label: 'Los Angeles', value: 'los_angeles', description: 'Population: 3,979,576' },
  { label: 'Louisville', value: 'louisville', description: 'Population: 617,638' },
  { label: 'Lubbock', value: 'lubbock', description: 'Population: 258,862' },
  { label: 'Madison', value: 'madison', description: 'Population: 259,680' },
  { label: 'Memphis', value: 'memphis', description: 'Population: 651,073' },
  { label: 'Mesa', value: 'mesa', description: 'Population: 508,958' },
  { label: 'Miami', value: 'miami', description: 'Population: 467,963' },
  { label: 'Milwaukee', value: 'milwaukee', description: 'Population: 590,157' },
  { label: 'Minneapolis', value: 'minneapolis', description: 'Population: 429,606' },
  { label: 'Nashville', value: 'nashville', description: 'Population: 670,820' },
  { label: 'New Orleans', value: 'new_orleans', description: 'Population: 390,144' },
  { label: 'New York', value: 'new_york', description: 'Population: 8,336,817' },
  { label: 'Newark', value: 'newark', description: 'Population: 282,011' },
  { label: 'Norfolk', value: 'norfolk', description: 'Population: 242,742' },
  { label: 'Oakland', value: 'oakland', description: 'Population: 433,031' },
  { label: 'Oklahoma City', value: 'oklahoma_city', description: 'Population: 655,057' },
  { label: 'Omaha', value: 'omaha', description: 'Population: 478,192' },
  { label: 'Orlando', value: 'orlando', description: 'Population: 287,442' },
  { label: 'Philadelphia', value: 'philadelphia', description: 'Population: 1,584,064' },
  { label: 'Phoenix', value: 'phoenix', description: 'Population: 1,680,992' },
  { label: 'Pittsburgh', value: 'pittsburgh', description: 'Population: 300,286' },
  { label: 'Plano', value: 'plano', description: 'Population: 287,677' },
  { label: 'Portland', value: 'portland', description: 'Population: 654,741' },
  { label: 'Raleigh', value: 'raleigh', description: 'Population: 474,069' },
  { label: 'Reno', value: 'reno', description: 'Population: 255,601' },
  { label: 'Richmond', value: 'richmond', description: 'Population: 230,436' },
  { label: 'Riverside', value: 'riverside', description: 'Population: 331,360' },
  { label: 'Rochester', value: 'rochester', description: 'Population: 205,695' },
  { label: 'Sacramento', value: 'sacramento', description: 'Population: 513,624' },
  {
    label: 'San Antonio',
    value: 'san_antonio',
    description: 'Population: 1,547,253',
    disabled: true,
    tooltipProps: { content: 'This city is unavailable' },
  },
  { label: 'San Bernardino', value: 'san_bernardino', description: 'Population: 215,784' },
  { label: 'San Diego', value: 'san_diego', description: 'Population: 1,423,851' },
  { label: 'San Francisco', value: 'san_francisco', description: 'Population: 881,549' },
  { label: 'San Jose', value: 'san_jose', description: 'Population: 1,021,795' },
  { label: 'Santa Ana', value: 'santa_ana', description: 'Population: 332,725' },
  { label: 'Scottsdale', value: 'scottsdale', description: 'Population: 258,069' },
  { label: 'Seattle', value: 'seattle', description: 'Population: 753,675' },
  { label: 'Spokane', value: 'spokane', description: 'Population: 222,081' },
  { label: 'St. Louis', value: 'st_louis', description: 'Population: 300,576' },
  { label: 'St. Paul', value: 'st_paul', description: 'Population: 308,096' },
  { label: 'St. Petersburg', value: 'st_petersburg', description: 'Population: 265,351' },
  { label: 'Stockton', value: 'stockton', description: 'Population: 312,697' },
  { label: 'Tampa', value: 'tampa', description: 'Population: 399,700' },
  { label: 'Toledo', value: 'toledo', description: 'Population: 272,779' },
  { label: 'Tucson', value: 'tucson', description: 'Population: 548,073' },
  { label: 'Tulsa', value: 'tulsa', description: 'Population: 401,190' },
  { label: 'Virginia Beach', value: 'virginia_beach', description: 'Population: 449,974' },
  { label: 'Washington', value: 'washington', description: 'Population: 705,749' },
  { label: 'Wichita', value: 'wichita', description: 'Population: 389,938' },
  { label: 'Winston-Salem', value: 'winston_salem', description: 'Population: 247,945' },
  { label: 'Yonkers', value: 'yonkers', description: 'Population: 200,370' },
];

export type Region = ComboboxSection<string, City>;

export const citiesByRegion: Region[] = [
  {
    label: 'Northeast',
    options: [
      { label: 'Boston', value: 'boston', description: 'Population: 692,600' },
      { label: 'Buffalo', value: 'buffalo', description: 'Population: 255,284' },
      { label: 'Jersey City', value: 'jersey_city', description: 'Population: 265,549' },
      { label: 'New York', value: 'new_york', description: 'Population: 8,336,817' },
      { label: 'Newark', value: 'newark', description: 'Population: 282,011' },
      { label: 'Philadelphia', value: 'philadelphia', description: 'Population: 1,584,064' },
      { label: 'Pittsburgh', value: 'pittsburgh', description: 'Population: 300,286' },
    ],
  },
  {
    label: 'South',
    options: [
      { label: 'Atlanta', value: 'atlanta', description: 'Population: 488,800' },
      { label: 'Charlotte', value: 'charlotte', description: 'Population: 885,708' },
      { label: 'Miami', value: 'miami', description: 'Population: 467,963' },
      { label: 'Nashville', value: 'nashville', description: 'Population: 670,820' },
      { label: 'Richmond', value: 'richmond', description: 'Population: 230,436' },
      { label: 'Tampa', value: 'tampa', description: 'Population: 399,700' },
      { label: 'Virginia Beach', value: 'virginia_beach', description: 'Population: 449,974' },
    ],
  },
  {
    label: 'Midwest',
    options: [
      { label: 'Chicago', value: 'chicago', description: 'Population: 2,693,976' },
      { label: 'Columbus', value: 'columbus', description: 'Population: 898,553' },
      { label: 'Detroit', value: 'detroit', description: 'Population: 670,031' },
      { label: 'Indianapolis', value: 'indianapolis', description: 'Population: 876,384' },
      { label: 'Kansas City', value: 'kansas_city', description: 'Population: 495,327' },
      { label: 'Milwaukee', value: 'milwaukee', description: 'Population: 590,157' },
      { label: 'Minneapolis', value: 'minneapolis', description: 'Population: 429,606' },
    ],
  },
  {
    label: 'West',
    options: [
      { label: 'Denver', value: 'denver', description: 'Population: 727,211' },
      { label: 'Las Vegas', value: 'las_vegas', description: 'Population: 651,319' },
      { label: 'Los Angeles', value: 'los_angeles', description: 'Population: 3,979,576' },
      { label: 'Phoenix', value: 'phoenix', description: 'Population: 1,680,992' },
      { label: 'Portland', value: 'portland', description: 'Population: 654,741' },
      { label: 'San Francisco', value: 'san_francisco', description: 'Population: 881,549' },
      { label: 'Seattle', value: 'seattle', description: 'Population: 753,675' },
    ],
  },
  {
    label: 'Southwest',
    options: [
      { label: 'Albuquerque', value: 'albuquerque', description: 'Population: 560,513' },
      { label: 'Austin', value: 'austin', description: 'Population: 978,908' },
      { label: 'Dallas', value: 'dallas', description: 'Population: 1,343,573' },
      { label: 'El Paso', value: 'el_paso', description: 'Population: 681,728' },
      { label: 'Houston', value: 'houston', description: 'Population: 2,320,268' },
      {
        label: 'San Antonio',
        value: 'san_antonio',
        description: 'Population: 1,547,253',
        disabled: true,
        tooltipProps: { content: 'This city is unavailable' },
      },
      { label: 'Tucson', value: 'tucson', description: 'Population: 548,073' },
    ],
  },
];

export const presetCities = [
  { label: 'Toronto', value: 'toronto', description: 'Population: 2,794,356' },
  { label: 'Vancouver', value: 'vancouver', description: 'Population: 631,486' },
  { label: 'Montreal', value: 'montreal', description: 'Population: 1,762,949' },
  { label: 'Calgary', value: 'calgary', description: 'Population: 1,306,784' },
  { label: 'Edmonton', value: 'edmonton', description: 'Population: 1,010,899' },
  { label: 'Ottawa', value: 'ottawa', description: 'Population: 1,017,449' },
];
