/* eslint-disable max-lines */
// Auto-generated file by https://github.com/melio/penny/actions/workflows/sync-brand-symbols.yml

export type BrandSymbolKey =
  | 'amazon'
  | 'amex'
  | 'bank-of-america'
  | 'capital-one'
  | 'chase'
  | 'citi-bank'
  | 'clover'
  | 'covantage'
  | 'credit-key'
  | 'diners'
  | 'discover'
  | 'dynamics365bc'
  | 'first-financial'
  | 'flex'
  | 'freshbooks'
  | 'gmail'
  | 'google-ads'
  | 'google'
  | 'gusto'
  | 'mastercard'
  | 'melio'
  | 'meta'
  | 'ms-dynamic-365'
  | 'ocean'
  | 'oracle-netsuite'
  | 'paypal'
  | 'quickbooks'
  | 'sage'
  | 'us-bank'
  | 'visa'
  | 'wafed'
  | 'wave'
  | 'wells-fargo'
  | 'xero';
