import { type SemanticColorTokens } from './defaultSemanticColors.types';

export const defaultSemanticColors: SemanticColorTokens = {
  background: {
    primary: '{global.neutral.100}',
    secondary: '{global.neutral.200}',
    brand: {
      primary: '{global.brand.700}',
      secondary: '{global.brand.100}',
    },
  },
  surface: {
    primary: {
      rest: '{global.neutral.100}',
      hover: '{global.neutral.300}',
      pressed: '{global.neutral.400}',
      selected: '{global.brand.100}',
      disabled: '{global.neutral.300}',
    },
    secondary: {
      rest: '{global.neutral.200}',
      hover: '{global.neutral.400}',
      pressed: '{global.neutral.500}',
      selected: '{global.brand.100}',
      disabled: '{global.neutral.300}',
    },
    inverse: '{global.neutral.1000}',
    tertiary: {
      rest: '{global.neutral.400}',
      hover: '{global.neutral.500}',
      pressed: '{global.neutral.600}',
      selected: '{global.neutral.100}',
      disabled: '{global.neutral.300}',
    },
  },
  action: {
    primary: {
      rest: '{global.brand.700}',
      hover: '{global.brand.800}',
      pressed: '{global.brand.900}',
      disabled: '{global.neutral.300}',
    },
    secondary: {
      rest: '{global.neutral.100}',
      hover: '{global.brand.100}',
      pressed: '{global.brand.200}',
      disabled: '{global.neutral.300}',
    },
    tertiary: {
      rest: '{global.neutral.100}',
      hover: '{global.neutral.300}',
      pressed: '{global.neutral.400}',
      disabled: '{global.neutral.300}',
    },
    success: {
      rest: '{global.success.700}',
      hover: '{global.success.800}',
      pressed: '{global.success.900}',
      disabled: '{global.neutral.300}',
    },
    criticalPrimary: {
      rest: '{global.critical.700}',
      hover: '{global.critical.800}',
      pressed: '{global.critical.900}',
      disabled: '{global.neutral.300}',
    },
    criticalSecondary: {
      rest: '{global.neutral.100}',
      hover: '{global.critical.100}',
      pressed: '{global.critical.200}',
      disabled: '{global.neutral.300}',
    },
    inversePrimary: {
      rest: '{global.neutral.100}',
      hover: '{global.neutral.A80}',
      pressed: '{global.neutral.A60}',
      disabled: '{global.neutral.300}',
    },
    inverseSecondary: {
      rest: '{global.neutral.A0}',
      hover: '{global.neutral.A15}',
      pressed: '{global.neutral.A35}',
      disabled: '{global.neutral.300}',
    },
    inverseTertiary: {
      rest: '{global.neutral.A0}',
      hover: '{global.neutral.A15}',
      pressed: '{global.neutral.A35}',
      disabled: '{global.neutral.300}',
    },
  },
  fill: {
    primary: '{global.neutral.100}',
    secondary: '{global.neutral.300}',
    tertiary: '{global.neutral.400}',
    disabled: '{global.neutral.300}',
    inverse: '{global.neutral.1000}',
    readOnly: '{global.neutral.700}',
    brand: {
      primary: '{global.brand.700}',
      secondary: '{global.brand.100}',
    },
    informative: {
      primary: '{global.informative.700}',
      secondary: '{global.informative.100}',
    },
    critical: {
      primary: '{global.critical.700}',
      secondary: '{global.critical.100}',
    },
    success: {
      primary: '{global.success.700}',
      secondary: '{global.success.100}',
    },
    warning: {
      primary: '{global.warning.700}',
      secondary: '{global.warning.100}',
    },
    decorative: {
      1: '{global.decorative.1}',
      2: '{global.decorative.2}',
      3: '{global.decorative.3}',
      4: '{global.decorative.4}',
      5: '{global.decorative.5}',
    },
  },
  text: {
    primary: '{global.neutral.1000}',
    secondary: '{global.neutral.700}',
    inverse: '{global.neutral.100}',
    disabled: '{global.neutral.500}',
    brand: {
      rest: '{global.brand.700}',
      hover: '{global.brand.800}',
      pressed: '{global.brand.900}',
      onColor: '{global.brand.900}',
    },
    informative: {
      rest: '{global.informative.700}',
      hover: '{global.informative.800}',
      pressed: '{global.informative.900}',
      onColor: '{global.informative.900}',
    },
    critical: {
      rest: '{global.critical.700}',
      hover: '{global.critical.800}',
      pressed: '{global.critical.900}',
      onColor: '{global.critical.900}',
    },
    success: {
      rest: '{global.success.700}',
      hover: '{global.success.800}',
      pressed: '{global.success.900}',
      onColor: '{global.success.900}',
    },
  },
  link: {
    primary: {
      rest: '{global.neutral.1000}',
      hover: '{global.neutral.1000}',
      pressed: '{global.neutral.700}',
      disabled: '{global.neutral.500}',
    },
    secondary: {
      rest: '{global.brand.700}',
      hover: '{global.brand.800}',
      pressed: '{global.brand.900}',
      disabled: '{global.neutral.500}',
    },
    inverse: {
      rest: '{global.neutral.100}',
      hover: '{global.neutral.A80}',
      pressed: '{global.neutral.A60}',
      disabled: '{global.neutral.A35}',
    },
  },
  border: {
    static: '{global.neutral.400}',
    interactive: {
      rest: '{global.neutral.600}',
      hover: '{global.neutral.1000}',
      selected: '{global.brand.700}',
      disabled: '{global.neutral.400}',
    },
    inverse: '{global.neutral.100}',
    brand: '{global.brand.700}',
    critical: '{global.critical.700}',
    success: '{global.success.700}',
    warning: '{global.warning.700}',
    informative: '{global.informative.700}',
    neutral: '{global.neutral.1000}',
  },
  icon: {
    primary: '{global.neutral.1000}',
    disabled: '{global.neutral.500}',
    readOnly: '{global.neutral.700}',
    inverse: '{global.neutral.100}',
    inverseDisabled: '{global.neutral.A35}',
    brand: '{global.brand.700}',
    informative: '{global.informative.700}',
    critical: '{global.critical.700}',
    success: '{global.success.700}',
    warning: '{global.warning.700}',
  },
  illustration: {
    background: '{global.neutral.100}',
    border: '{global.neutral.1000}',
    critical: '{global.critical.700}',
    success: '{global.success.700}',
    brand: {
      primary: '{global.brand.700}',
      secondary: '{global.brand.100}',
    },
  },
  focus: {
    primary: '{global.focus.primary}',
    inverse: '{global.focus.inverse}',
  },
};
